### ISSUE TITLE
Admin top-nav contains too many items

### ISSUE THREAD

**Issue by reinefjord** [teknologkoren/Strequelistan#6]
_From @Victorystick on February 14, 2017 22:34_

The body-padding hack should be removed. It is there because of the varying size of the top bar; caused by there being too many items in the top-nav when signed in as an admin. It makes the styling of the rest of the site unwieldy. It causes a bunch of bugs in it's current form.

_Copied from original issue: Alge/Strecklista#55_

**Comment by Victorystick** [comment]
Fixed AFAIK
