### ISSUE TITLE
Make profile pictures not act like soviet russia

### ISSUE THREAD

**Issue by reinefjord** [teknologkoren/Strequelistan#7]
_From @Ormbunke on February 15, 2017 22:10_

It doesn't work ;)

Profile pictures don't show properly

_Copied from original issue: Alge/Strecklista#61_

**Comment by reinefjord** [comment]
_From @Ormbunke on February 15, 2017 22:13_

Is actually a feature

**Comment by reinefjord** [comment]
_From @Victorystick on February 15, 2017 22:14_

Yeah. Working as intended.

**Comment by reinefjord** [comment]
Vafan håller ni på med?

Ormbunke <notifications@github.com> skrev: (15 februari 2017 23:13:40 CET)

**Comment by reinefjord** [comment]
_From @Ormbunke on February 15, 2017 22:19_

https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

Perhaps?

**Comment by reinefjord** [comment]
_From @Alge on February 15, 2017 22:20_

Kom igen... Det här är faktiskt ett problem som måste lösas

**Comment by reinefjord** [comment]
_From @Alge on February 23, 2017 12:19_

Skulle du kunna fixa så att hela bilderna visas? @Victorystick

**Comment by Victorystick** [comment]
Hela bilderna, nej. Det får du klicka på den för. Men rotationen bör vara rätt. 😝
